name: pelis_ya
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.3.4
  build_runner: ^2.4.14
  card_swiper: ^3.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  intl: ^0.20.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
